---
- name: "restart kubernetes master services"
  service:
    name: "{{ item }}"
    state: "restarted"
  with_items:
    - "etcd"
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"
