- name: "minion upgrade"
  command: "rpm-ostree upgrade"

#- name: "minion reboot"
#  command: "rpm-ostree upgrade && exit"

- name: start kubernetes cluster
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "etcd"
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"
